import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export type ExportableResults = {
  title: string;
  stats: { label: string; value: string; badge?: { text: string } }[];
  interpretation: string;
  apaOutput?: string;
};

export type ExportFormat = "pdf" | "csv" | "excel";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function fileBase(title: string): string {
  return `${slugify(title) || "analysis"}-results`;
}

function escapeCsvCell(value: string): string {
  if (/[",\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function downloadBlob(content: BlobPart, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function exportResultsToPdf({
  title,
  stats,
  interpretation,
  apaOutput,
}: ExportableResults): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.text("dataclue", margin, y);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text("Statistical Analysis Report", margin, y + 7);

  y += 18;
  doc.setFontSize(14);
  doc.setTextColor(37, 99, 235);
  doc.text(title, margin, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);

  y += 8;
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Statistic", "Value"]],
    body: stats.map((stat) => [
      stat.label,
      stat.badge ? `${stat.value} (${stat.badge.text})` : stat.value,
    ]),
    theme: "striped",
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 0: { cellWidth: 80 }, 1: { cellWidth: "auto" } },
  });

  const tableEnd = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
    ?.finalY;
  y = (tableEnd ?? y) + 12;

  const addSection = (heading: string, body: string) => {
    const lines = doc.splitTextToSize(body, contentWidth);
    const blockHeight = 8 + lines.length * 5;

    if (y + blockHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(22, 101, 52);
    doc.text(heading, margin, y);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;
  };

  addSection("Interpretation", interpretation);

  if (apaOutput) {
    doc.setTextColor(30, 58, 138);
    addSection("APA Output", apaOutput);
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Generated by dataclue",
    margin,
    doc.internal.pageSize.getHeight() - 10,
  );

  doc.save(`${fileBase(title)}.pdf`);
}

export function exportResultsToCsv({
  title,
  stats,
  interpretation,
  apaOutput,
}: ExportableResults): void {
  const rows: string[][] = [
    ["Field", "Value"],
    ["Test", title],
    ["Generated", new Date().toLocaleString()],
    ["Source", "dataclue"],
    [],
    ["Statistic", "Value", "Note"],
    ...stats.map((stat) => [
      stat.label,
      stat.value,
      stat.badge?.text ?? "",
    ]),
    [],
    ["Section", "Content"],
    ["Interpretation", interpretation],
  ];

  if (apaOutput) {
    rows.push(["APA Output", apaOutput]);
  }

  const csv = rows
    .map((row) => row.map((cell) => escapeCsvCell(cell ?? "")).join(","))
    .join("\r\n");

  downloadBlob(csv, `${fileBase(title)}.csv`, "text/csv;charset=utf-8;");
}

export function exportResultsToExcel({
  title,
  stats,
  interpretation,
  apaOutput,
}: ExportableResults): void {
  const rows: (string | number)[][] = [
    ["dataclue — Statistical Analysis Report"],
    ["Test", title],
    ["Generated", new Date().toLocaleString()],
    [],
    ["Statistic", "Value", "Note"],
    ...stats.map((stat) => [
      stat.label,
      stat.value,
      stat.badge?.text ?? "",
    ]),
    [],
    ["Interpretation"],
    [interpretation],
  ];

  if (apaOutput) {
    rows.push([], ["APA Output"], [apaOutput]);
  }

  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  worksheet["!cols"] = [{ wch: 28 }, { wch: 40 }, { wch: 20 }];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Results");
  XLSX.writeFile(workbook, `${fileBase(title)}.xlsx`);
}

export function exportResults(
  data: ExportableResults,
  format: ExportFormat,
): void {
  switch (format) {
    case "pdf":
      exportResultsToPdf(data);
      break;
    case "csv":
      exportResultsToCsv(data);
      break;
    case "excel":
      exportResultsToExcel(data);
      break;
  }
}
